# This is a basic workflow to help you get started with Actions

name: Build Window RISC-V Toolchain (RV32im)

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      toolchain_tag: 
        description: 'Git tag to build'
        required: true
        default: '2025.05.30'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    timeout-minutes: 240

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            git
            mingw-w64-x86_64-make
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-autotools
            mingw-w64-x86_64-python
            mingw-w64-x86_64-texinfo
      
      - name: Clone Toolchain
        shell: msys2 {0}
        run: |
          git clone --depth 50 --branch ${{ github.event.inputs.toolchain_tag || '2025.05.30' }} https://github.com/riscv-collab/riscv-gnu-toolchain
          cd riscv-gnu-toolchain
          git submodule update --init --depth 1 --recursive
          
      - name: Build Newlib Toolchain
        shell: msys2 {0}
        run: |
          cd riscv-gnu-toolchain

          ./configure \
            --prefix=/c/riscv-newlib-rv32im \
            --with-arch=rv32im \
            --enable-multilib \
            --with-newlib \
            --with-languages=c,c++
          make -j $NUMBER_OF_PROCESSORS

      - name: Create Portable Package
        shell: bash
        run: |
          7z a -mmt8 riscv-newlib-toolchain-win-x64-rv32im.zip /c/riscv-newlib-rv32im/*

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: riscv-unknown-elf-toolchan-rv32im
          path: riscv-newlib-toolchain-win-x64-rv32im.zip
